trigger:
 branches:
    include:
    - master
 tags:
    include:
    - release*

pool:
  vmImage: ubuntu-latest
  

steps:

 - checkout: self
   submodules: true
   persistCredentials: true
   # condition: contains(variables['Build.SourceBranch'], 'refs/tags/release')

 - task: PowerShell@2
   displayName: 'Replace Package Versions in template.json'
   inputs:
    filePath: 'template-versions.ps1'

 - script: dotnet build --configuration release
   displayName: 'Build All Projects'

 - script: dotnet pack ShiftFrameworkTestingTools/ShiftFrameworkTestingTools --configuration Release --output $(Build.ArtifactStagingDirectory)/Framework
   displayName: 'pack ShiftFrameworkTestingTools'

 - script: dotnet pack ShiftIdentity/ShiftIdentity.AspNetCore --configuration Release --output $(Build.ArtifactStagingDirectory)/Framework
   displayName: 'pack ShiftIdentity.AspNetCore'

 - script: dotnet pack ShiftIdentity/ShiftIdentity.Data --configuration Release --output $(Build.ArtifactStagingDirectory)/Framework
   displayName: 'pack ShiftIdentity.Data'

 - script: dotnet pack ShiftIdentity/ShiftIdentity.Blazor --configuration Release --output $(Build.ArtifactStagingDirectory)/Framework
   displayName: 'pack ShiftIdentity.Blazor'

 - script: dotnet pack ShiftIdentity/ShiftIdentity.Core --configuration Release --output $(Build.ArtifactStagingDirectory)/Framework
   displayName: 'pack ShiftIdentity.Core'

 - script: dotnet pack ShiftIdentity/ShiftIdentity.Dashboard.AspNetCore --configuration Release --output $(Build.ArtifactStagingDirectory)/Framework
   displayName: 'pack ShiftIdentity.Dashboard.AspNetCore'

 - script: dotnet pack ShiftIdentity/ShiftIdentity.Dashboard.Blazor --configuration Release --output $(Build.ArtifactStagingDirectory)/Framework
   displayName: 'pack ShiftIdentity.Dashboard.Blazor'

 - script: dotnet pack ShiftEntity/ShiftEntity.Core --configuration Release --output $(Build.ArtifactStagingDirectory)/Framework
   displayName: 'pack ShiftEntity.Core'

 - script: dotnet pack ShiftEntity/ShiftEntity.CosmosDbReplication --configuration Release --output $(Build.ArtifactStagingDirectory)/Framework
   displayName: 'pack ShiftEntity.CosmosDbReplication'

 - script: dotnet pack ShiftEntity/ShiftEntity.EFCore --configuration Release --output $(Build.ArtifactStagingDirectory)/Framework
   displayName: 'pack ShiftEntity.EFCore'

 - script: dotnet pack ShiftEntity/ShiftEntity.Model --configuration Release --output $(Build.ArtifactStagingDirectory)/Framework
   displayName: 'pack ShiftEntity.Model'

 - script: dotnet pack ShiftEntity/ShiftEntity.Web --configuration Release --output $(Build.ArtifactStagingDirectory)/Framework
   displayName: 'pack ShiftEntity.Web'

 - script: dotnet pack ShiftEntity/ShiftEntity.Print --configuration Release --output $(Build.ArtifactStagingDirectory)/Framework
   displayName: 'pack ShiftEntity.Print'

 - script: dotnet pack ShiftBlazor/ShiftBlazor --configuration Release --output $(Build.ArtifactStagingDirectory)/Framework
   displayName: 'pack ShiftBlazor'

 - script: dotnet pack ShiftTemplates --configuration Release --output $(Build.ArtifactStagingDirectory)/Framework
   displayName: 'pack ShiftTemplates'

 - script: dotnet test TypeAuth\TypeAuth.Core.Tests
   displayName: 'Test TypeAuth.Core'

 - script: dotnet test TypeAuth\TypeAuth.AspNetCore.Tests
   displayName: 'Test TypeAuth.AspNetCore'

 - script: dotnet pack TypeAuth/TypeAuth.Core --configuration Release --output $(Build.ArtifactStagingDirectory)/TypeAuth
   displayName: 'pack TypeAuth.Core'

 - script: dotnet pack TypeAuth/TypeAuth.Blazor --configuration Release --output $(Build.ArtifactStagingDirectory)/TypeAuth
   displayName: 'pack TypeAuth.Blazor'

 - script: dotnet pack TypeAuth/TypeAuth.AspNetCore --configuration Release --output $(Build.ArtifactStagingDirectory)/TypeAuth
   displayName: 'pack TypeAuth.AspNetCore'

 - script: dotnet test AzureFunctionsAspNetCoreAuthorization\Tests
   displayName: 'Test Azure Functions AspNetCore Authorization'

 - script: dotnet pack AzureFunctionsAspNetCoreAuthorization/ShiftSoftware.Azure.Functions.AspNetCore.Authorization --configuration Release --output $(Build.ArtifactStagingDirectory)/AzureFunctionsAspNetCoreAuthorization
   displayName: 'pack Azure Functions AspNetCore Authorization'


 - task: NuGetCommand@2
   displayName: 'Push TypeAuth Packages' 
   inputs:
    command: 'push'
    packagesToPush: '$(Build.ArtifactStagingDirectory)/TypeAuth/**/*.nupkg;!$(Build.ArtifactStagingDirectory)/TypeAuth/**/*.symbols.nupkg'
    nuGetFeedType: 'external'
    publishFeedCredentials: 'NuGet.org'
    allowPackageConflicts: true


 - task: NuGetCommand@2
   displayName: 'Push Azure Functions AspNetCore Authorization' 
   inputs:
    command: 'push'
    packagesToPush: '$(Build.ArtifactStagingDirectory)/AzureFunctionsAspNetCoreAuthorization/**/*.nupkg;!$(Build.ArtifactStagingDirectory)/AzureFunctionsAspNetCoreAuthorization/**/*.symbols.nupkg'
    nuGetFeedType: 'external'
    publishFeedCredentials: 'NuGet.org'
    allowPackageConflicts: true


 - task: NuGetCommand@2
   displayName: 'Push Framework Packages' 
   inputs:
    command: 'push'
    packagesToPush: '$(Build.ArtifactStagingDirectory)/Framework/**/*.nupkg;!$(Build.ArtifactStagingDirectory)/Framework/**/*.symbols.nupkg'
    nuGetFeedType: 'external'
    publishFeedCredentials: 'NuGet.org'