trigger:
 branches:
    include:
    - master
 tags:
    include:
    - release*

pool:
  vmImage: ubuntu-latest
  

steps:

 - checkout: self
   submodules: true
   persistCredentials: true
   # condition: contains(variables['Build.SourceBranch'], 'refs/tags/release')

 - script: dotnet build --configuration release
   displayName: 'Build All Projects'

 - script: dotnet pack TypeAuth/TypeAuth.Core --configuration Release --output $(Build.ArtifactStagingDirectory)
   displayName: 'pack TypeAuth.Core'

 - script: dotnet pack TypeAuth/TypeAuth.Blazor --configuration Release --output $(Build.ArtifactStagingDirectory)
   displayName: 'pack TypeAuth.Blazor'

 - script: dotnet pack TypeAuth/TypeAuth.AspNetCore --configuration Release --output $(Build.ArtifactStagingDirectory)
   displayName: 'pack TypeAuth.AspNetCore'

 - script: dotnet pack ShiftFrameworkTestingTools/ShiftFrameworkTestingTools --configuration Release --output $(Build.ArtifactStagingDirectory)
   displayName: 'pack ShiftFrameworkTestingTools'

 - script: dotnet pack ShiftIdentity/ShiftIdentity.AspNetCore --configuration Release --output $(Build.ArtifactStagingDirectory)
   displayName: 'pack ShiftIdentity.AspNetCore'

 - script: dotnet pack ShiftIdentity/ShiftIdentity.Data --configuration Release --output $(Build.ArtifactStagingDirectory)
   displayName: 'pack ShiftIdentity.Data'

 - script: dotnet pack ShiftIdentity/ShiftIdentity.Blazor --configuration Release --output $(Build.ArtifactStagingDirectory)
   displayName: 'pack ShiftIdentity.Blazor'

 - script: dotnet pack ShiftIdentity/ShiftIdentity.Core --configuration Release --output $(Build.ArtifactStagingDirectory)
   displayName: 'pack ShiftIdentity.Core'

 - script: dotnet pack ShiftIdentity/ShiftIdentity.Dashboard.AspNetCore --configuration Release --output $(Build.ArtifactStagingDirectory)
   displayName: 'pack ShiftIdentity.Dashboard.AspNetCore'

 - script: dotnet pack ShiftIdentity/ShiftIdentity.Dashboard.Blazor --configuration Release --output $(Build.ArtifactStagingDirectory)
   displayName: 'pack ShiftIdentity.Dashboard.Blazor'

 - script: dotnet pack ShiftEntity/ShiftEntity.Core --configuration Release --output $(Build.ArtifactStagingDirectory)
   displayName: 'pack ShiftEntity.Core'

 - script: dotnet pack ShiftEntity/ShiftEntity.CosmosDbReplication --configuration Release --output $(Build.ArtifactStagingDirectory)
   displayName: 'pack ShiftEntity.CosmosDbReplication'

 - script: dotnet pack ShiftEntity/ShiftEntity.EFCore --configuration Release --output $(Build.ArtifactStagingDirectory)
   displayName: 'pack ShiftEntity.EFCore'

 - script: dotnet pack ShiftEntity/ShiftEntity.Model --configuration Release --output $(Build.ArtifactStagingDirectory)
   displayName: 'pack ShiftEntity.Model'

 - script: dotnet pack ShiftEntity/ShiftEntity.Web --configuration Release --output $(Build.ArtifactStagingDirectory)
   displayName: 'pack ShiftEntity.Web'

 - script: dotnet pack ShiftEntity/ShiftEntity.Print --configuration Release --output $(Build.ArtifactStagingDirectory)
   displayName: 'pack ShiftEntity.Print'

 - script: dotnet pack ShiftBlazor/ShiftBlazor --configuration Release --output $(Build.ArtifactStagingDirectory)
   displayName: 'pack ShiftBlazor'

 - script: dotnet pack ShiftTemplates --configuration Release --output $(Build.ArtifactStagingDirectory)
   displayName: 'pack ShiftTemplates'

 - task: NuGetCommand@2
   inputs:
    command: 'push'
    packagesToPush: '$(Build.ArtifactStagingDirectory)/**/*.nupkg;!$(Build.ArtifactStagingDirectory)/**/*.symbols.nupkg'
    nuGetFeedType: 'external'
    publishFeedCredentials: 'NuGet.org'